[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Referrer-Policy = "no-referrer"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

[[redirects]]
  from = "/wp-login.php"
  to = "/"
  status = 301


[[redirects]]
from = "/assets/downloads/red-sea-routes-ru"
to = "https://drive.google.com/file/d/1iEAt1eR1HVwoWBg-Gr7V4C3iyTEbmsXq/view"
status = 302
force = true

[[redirects]]
from = "/assets/downloads/red-sea-routes-en"
to = "https://drive.google.com/file/d/11lQlAmxvSS4XlyoPqyYF0dCSNwle5Elx/view"
status = 302
force = true



[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
